name: Clojure/ClojureScript CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Clojure/ClojureScript dependencies
      run: lein deps
    - name: Install node.js dependencies
      run: npm install
    - name: Run all tests
      run: lein test-build
      env:
        HEROKU_ENV: test
